spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rootroot
    username: root
    url: jdbc:mysql://localhost:3306/new_schema
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8080
  servlet:
    context-path: /

