spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rootroot
    username: root
    url: jdbc:mysql://localhost:3306/new_schema
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  lifetime: 30m
  secret: 984dkdkh33ttte71ebnj4672crh569vvf47vmbmn99

logging:
  level:
    root: INFO